# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
builds:
- env:
  - CGO_ENABLED=0 # this is needed otherwise the Docker image build is faulty
  goarch:
  - amd64
  goos:
  - linux

archives:
- format: binary
  name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-snapshot"

dockers:
- image_templates:
  # TODO: Adjust image locations
  - "ghcr.io/vshn/go-bootstrap:v{{ .Version }}"

    # For prereleases, updating `latest` does not make sense.
    # Only the image for the exact version should be pushed.
  - "{{ if not .Prerelease }}ghcr.io/vshn/go-bootstrap:latest{{ end }}"

release:
  prerelease: auto
