---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-minio-crossplane-io-v1-bucket
  failurePolicy: Fail
  name: buckets.minio.crossplane.io
  rules:
  - apiGroups:
    - minio.crossplane.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - buckets
  sideEffects: None
