apiVersion: minio.crossplane.io/v1
kind: Bucket
metadata:
  creationTimestamp: null
  name: bucket-local-dev
spec:
  forProvider:
    region: us-east-1
  providerConfigRef:
    name: provider-config
status:
  atProvider: {}
