apiVersion: v1
data:
  AWS_ACCESS_KEY_ID: bWluaW9hZG1pbg==
  AWS_SECRET_ACCESS_KEY: bWluaW9hZG1pbg==
kind: Secret
metadata:
  creationTimestamp: null
  name: minio-secret
  namespace: crossplane-system
