apiVersion: minio.m.crossplane.io/v1beta1
kind: Policy
metadata:
  name: mypolicy
spec:
  forProvider:
    allowBucket: bucket-local-dev
  providerConfigRef:
    kind: ProviderConfig
    name: provider-config
status:
  atProvider: {}
