apiVersion: minio.m.crossplane.io/v1beta1
kind: User
metadata:
  name: devuser
spec:
  forProvider: {}
  providerConfigRef:
    kind: ProviderConfig
    name: provider-config
  writeConnectionSecretToRef:
    name: devuser
status:
  atProvider: {}
