apiVersion: minio.m.crossplane.io/v1beta1
kind: Bucket
metadata:
  name: bucket-local-dev
spec:
  forProvider:
    region: us-east-1
  providerConfigRef:
    kind: ProviderConfig
    name: provider-config
status:
  atProvider: {}
