---
apiVersion: minio.crossplane.io/v1
kind: ServiceAccount
metadata:
  name: example-service-account
spec:
  providerConfigRef:
    name: minio-provider-config
  forProvider:
    name: "Example Service Account"
    description: "Service account for automated MinIO access"
    # Optional: JSON policy document to restrict permissions
    policy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Action": [
              "s3:GetObject",
              "s3:PutObject",
              "s3:ListBucket"
            ],
            "Resource": [
              "arn:aws:s3:::example-bucket",
              "arn:aws:s3:::example-bucket/*"
            ]
          }
        ]
      }
  writeConnectionSecretsToRef:
    name: example-service-account-secret
    namespace: default
