apiVersion: minio.crossplane.io/v1
kind: ServiceAccount
metadata:
  name: example-serviceaccount
  annotations:
    crossplane.io/external-name: ""  # Will be set automatically to the access key
spec:
  forProvider:
    # Parent user that this service account will be created under
    # This user must exist in MinIO
    parentUser: "example-user"
    
    # Optional: Name/description for the service account
    # Defaults to metadata.name if not specified
    serviceAccountName: "app-access-key"
    
    # Optional: Human readable description
    description: "Service account for application access"
    
    # Optional: Additional policies to assign to the service account
    # These are in addition to the parent user's policies
    policies:
      - "readwrite"
      - "diagnostics"
    
    # Optional: Expiration time (RFC3339 format)
    # If not set, the service account will not expire
    # expiry: "2024-12-31T23:59:59Z"
  
  # Reference to the ProviderConfig
  providerConfigRef:
    name: default
  
  # Connection secret where credentials will be stored
  writeConnectionSecretsToRef:
    name: serviceaccount-credentials
    namespace: default
---
# Example secret that will be created with the service account credentials
# This is created automatically by Crossplane
apiVersion: v1
kind: Secret
metadata:
  name: serviceaccount-credentials
  namespace: default
type: Opaque
# Data will be populated automatically with:
# accessKey: <base64-encoded-access-key>
# secretKey: <base64-encoded-secret-key>  
# parentUser: <base64-encoded-parent-user>