---
apiVersion: minio.crossplane.io/v1
kind: ServiceAccount
metadata:
  name: example-service-account
  annotations:
    crossplane.io/external-name: my-service-account
spec:
  providerConfigRef:
    name: minio-provider-config
  forProvider:
    # Optional: Specify the target user (if not specified, will use the provider config user)
    targetUser: "example-user"
    # Optional: Specify a custom access key (if not specified, MinIO will generate one)
    accessKey: "my-custom-access-key"
    # Optional: Specify a custom secret key (if not specified, MinIO will generate one)
    # secretKey: "my-custom-secret-key"
    name: "Example Service Account"
    description: "Service account for automated MinIO access"
    # Optional: JSON policy document to restrict permissions
    policy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Action": [
              "s3:GetObject",
              "s3:PutObject"
            ],
            "Resource": [
              "arn:aws:s3:::example-bucket/*"
            ]
          }
        ]
      }
    # Optional: Expiration time for the service account (ISO 8601 format)
    # expiration: "2025-12-31T23:59:59Z"
  writeConnectionSecretsToRef:
    name: example-service-account-secret
    namespace: default
---
apiVersion: minio.crossplane.io/v1
kind: ServiceAccount
metadata:
  name: simple-service-account
spec:
  providerConfigRef:
    name: minio-provider-config
  forProvider:
    name: "Simple Service Account"
    description: "Service account with inherited permissions"
    # This service account will inherit permissions from the parent user
  writeConnectionSecretsToRef:
    name: simple-service-account-secret
    namespace: default
