# Example of using ServiceAccount in a Crossplane Composition
# This shows how to create a complete MinIO setup with user, bucket, and service account
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: minio-app-resources
spec:
  compositeTypeRef:
    apiVersion: example.io/v1alpha1
    kind: XMinioAppResources
  resources:
    # Create the parent user
    - name: user
      base:
        apiVersion: minio.crossplane.io/v1
        kind: User
        spec:
          forProvider:
            policies:
              - readwrite
          providerConfigRef:
            name: default
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.userName
          toFieldPath: metadata.name
        - type: FromCompositeFieldPath
          fromFieldPath: spec.userName
          toFieldPath: spec.forProvider.name
    
    # Create the application bucket
    - name: bucket
      base:
        apiVersion: minio.crossplane.io/v1
        kind: Bucket
        spec:
          forProvider:
            region: us-east-1
          providerConfigRef:
            name: default
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.bucketName
          toFieldPath: metadata.name
        - type: FromCompositeFieldPath
          fromFieldPath: spec.bucketName
          toFieldPath: spec.forProvider.name
    
    # Create service account for the application
    - name: serviceaccount
      base:
        apiVersion: minio.crossplane.io/v1
        kind: ServiceAccount
        spec:
          forProvider:
            policies:
              - readwrite
            description: "Composed service account for application"
          providerConfigRef:
            name: default
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.serviceAccountName
          toFieldPath: metadata.name
        - type: FromCompositeFieldPath
          fromFieldPath: spec.userName
          toFieldPath: spec.forProvider.parentUser
        - type: FromCompositeFieldPath
          fromFieldPath: spec.namespace
          toFieldPath: spec.writeConnectionSecretToRef.namespace
        - type: CombineFromComposite
          combine:
            variables:
              - fromFieldPath: spec.serviceAccountName
            strategy: string
            string:
              fmt: "%s-credentials"
          toFieldPath: spec.writeConnectionSecretToRef.name
      connectionDetails:
        - name: accessKey
          fromConnectionSecretKey: accessKey
        - name: secretKey
          fromConnectionSecretKey: secretKey
        - name: parentUser
          fromConnectionSecretKey: parentUser