#!/bin/bash
# Verifies the controller wrote a usable connection secret.
#
# The secret's values are generated by the controller, so they cannot be asserted
# ahead of time. kuttl's exact match is not usable here and its inline command
# steps are executed word by word rather than through a shell, so this lives in a
# script instead.
set -euo pipefail

secret="${1:-test-serviceaccount-secret}"
namespace="${2:-default}"

name=$(kubectl get secret -n "$namespace" "$secret" -o jsonpath='{.metadata.name}')
test -n "$name"

type=$(kubectl get secret -n "$namespace" "$secret" -o jsonpath='{.type}')
if [ "$type" != "connection.crossplane.io/v1alpha1" ]; then
  echo "unexpected secret type: $type" >&2
  exit 1
fi

for key in AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY; do
  value=$(kubectl get secret -n "$namespace" "$secret" -o "jsonpath={.data.$key}" | base64 -d)
  if [ -z "$value" ]; then
    echo "secret key $key is empty" >&2
    exit 1
  fi
  echo "$key is populated (${#value} chars)"
done
