name: Test

on:
  pull_request:
    branches:
      - "*"
    paths-ignore:
      - docs/**
  push:
    branches:
      - master
    paths-ignore:
      - docs/**

env:
  GO_VERSION: '1.24.5'

jobs:
  unit-tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Cache Go Dependencies
        uses: actions/cache@v4
        with:
          path: .work/pkg
          key: ${{ runner.os }}-pkg-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-pkg-

      - name: Cache Go Build
        uses: actions/cache@v4
        with:
          path: .work/go
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-

      - name: Vendor Dependencies
        run: make vendor vendor.check

      - name: Run Unit Tests
        run: make test

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: "_output/tests/*.xml"

      - name: Upload Coverage
        uses: codecov/codecov-action@v4
        with:
          file: _output/tests/coverage.txt
          fail_ci_if_error: false
